// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: player_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PLAYER_STATE int32

const (
	PLAYER_STATE_STANDING  PLAYER_STATE = 0
	PLAYER_STATE_CROUCHING PLAYER_STATE = 1
	PLAYER_STATE_JUMPING   PLAYER_STATE = 2
)

// Enum value maps for PLAYER_STATE.
var (
	PLAYER_STATE_name = map[int32]string{
		0: "STANDING",
		1: "CROUCHING",
		2: "JUMPING",
	}
	PLAYER_STATE_value = map[string]int32{
		"STANDING":  0,
		"CROUCHING": 1,
		"JUMPING":   2,
	}
)

func (x PLAYER_STATE) Enum() *PLAYER_STATE {
	p := new(PLAYER_STATE)
	*p = x
	return p
}

func (x PLAYER_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAYER_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_player_data_proto_enumTypes[0].Descriptor()
}

func (PLAYER_STATE) Type() protoreflect.EnumType {
	return &file_player_data_proto_enumTypes[0]
}

func (x PLAYER_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PLAYER_STATE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PLAYER_STATE(num)
	return nil
}

// Deprecated: Use PLAYER_STATE.Descriptor instead.
func (PLAYER_STATE) EnumDescriptor() ([]byte, []int) {
	return file_player_data_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         *string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id           *uint32            `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	PlayerColor  *string            `protobuf:"bytes,3,opt,name=player_color,json=playerColor" json:"player_color,omitempty"`
	RotationY    *float32           `protobuf:"fixed32,4,req,name=rotation_y,json=rotationY" json:"rotation_y,omitempty"`
	RotationX    *float32           `protobuf:"fixed32,5,req,name=rotation_x,json=rotationX" json:"rotation_x,omitempty"`
	Health       *float32           `protobuf:"fixed32,6,req,name=health" json:"health,omitempty"`
	CurrentSpell *uint32            `protobuf:"varint,7,req,name=current_spell,json=currentSpell" json:"current_spell,omitempty"`
	Casting      *bool              `protobuf:"varint,8,req,name=casting" json:"casting,omitempty"`
	Pos          []*Player_Position `protobuf:"bytes,9,rep,name=pos" json:"pos,omitempty"`
	PlayerState  *PLAYER_STATE      `protobuf:"varint,10,req,name=player_state,json=playerState,enum=tutorial.PLAYER_STATE" json:"player_state,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_data_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Player) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Player) GetPlayerColor() string {
	if x != nil && x.PlayerColor != nil {
		return *x.PlayerColor
	}
	return ""
}

func (x *Player) GetRotationY() float32 {
	if x != nil && x.RotationY != nil {
		return *x.RotationY
	}
	return 0
}

func (x *Player) GetRotationX() float32 {
	if x != nil && x.RotationX != nil {
		return *x.RotationX
	}
	return 0
}

func (x *Player) GetHealth() float32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *Player) GetCurrentSpell() uint32 {
	if x != nil && x.CurrentSpell != nil {
		return *x.CurrentSpell
	}
	return 0
}

func (x *Player) GetCasting() bool {
	if x != nil && x.Casting != nil {
		return *x.Casting
	}
	return false
}

func (x *Player) GetPos() []*Player_Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Player) GetPlayerState() PLAYER_STATE {
	if x != nil && x.PlayerState != nil {
		return *x.PlayerState
	}
	return PLAYER_STATE_STANDING
}

type Players struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player []*Player `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
}

func (x *Players) Reset() {
	*x = Players{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_player_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_player_data_proto_rawDescGZIP(), []int{1}
}

func (x *Players) GetPlayer() []*Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type Player_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
}

func (x *Player_Position) Reset() {
	*x = Player_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_Position) ProtoMessage() {}

func (x *Player_Position) ProtoReflect() protoreflect.Message {
	mi := &file_player_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_Position.ProtoReflect.Descriptor instead.
func (*Player_Position) Descriptor() ([]byte, []int) {
	return file_player_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Player_Position) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Player_Position) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Player_Position) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

var File_player_data_proto protoreflect.FileDescriptor

var file_player_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x82, 0x03,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x06, 0x20, 0x02, 0x28, 0x02, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x12, 0x39, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x2e, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x34, 0x0a, 0x08,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52,
	0x01, 0x7a, 0x22, 0x33, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2a, 0x38, 0x0a, 0x0c, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x52, 0x4f, 0x55, 0x43, 0x48, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4a, 0x55, 0x4d, 0x50, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_player_data_proto_rawDescOnce sync.Once
	file_player_data_proto_rawDescData = file_player_data_proto_rawDesc
)

func file_player_data_proto_rawDescGZIP() []byte {
	file_player_data_proto_rawDescOnce.Do(func() {
		file_player_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_player_data_proto_rawDescData)
	})
	return file_player_data_proto_rawDescData
}

var file_player_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_player_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_player_data_proto_goTypes = []interface{}{
	(PLAYER_STATE)(0),       // 0: tutorial.PLAYER_STATE
	(*Player)(nil),          // 1: tutorial.Player
	(*Players)(nil),         // 2: tutorial.Players
	(*Player_Position)(nil), // 3: tutorial.Player.Position
}
var file_player_data_proto_depIdxs = []int32{
	3, // 0: tutorial.Player.pos:type_name -> tutorial.Player.Position
	0, // 1: tutorial.Player.player_state:type_name -> tutorial.PLAYER_STATE
	1, // 2: tutorial.Players.player:type_name -> tutorial.Player
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_player_data_proto_init() }
func file_player_data_proto_init() {
	if File_player_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_player_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Players); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_player_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_data_proto_goTypes,
		DependencyIndexes: file_player_data_proto_depIdxs,
		EnumInfos:         file_player_data_proto_enumTypes,
		MessageInfos:      file_player_data_proto_msgTypes,
	}.Build()
	File_player_data_proto = out.File
	file_player_data_proto_rawDesc = nil
	file_player_data_proto_goTypes = nil
	file_player_data_proto_depIdxs = nil
}
